version: '3.3'
services:
 nut:
   container_name: influx-nut
   restart: unless-stopped
   image: influxdb/nut
   environment:
      - TZ=America/Santiago
   volumes:
      - './influx_nut.json:/etc/influx_nut.json:ro'
      - '/etc/localtime:/etc/localtime:ro'
   networks:
      - dockerlink
   extra_hosts:
      host: x.x.x.21
networks:
 dockerlink:
   external:
     name: dockerlink

